In [3]:
# crete model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
        
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        
        return out
         
        

In [4]:
## create datset
features = torch.rand(10,5)

# create model

model = Model(features.shape[1])

# call model for forward pass

model(features)

tensor([[0.5837],
        [0.5270],
        [0.5643],
        [0.5781],
        [0.6325],
        [0.5047],
        [0.5576],
        [0.5452],
        [0.5016],
        [0.5841]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0558, -0.4242, -0.1257,  0.2649,  0.0470]], requires_grad=True)

In [7]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.3602], requires_grad=True)

In [8]:
from torchinfo import summary

In [9]:
summary(model,input_size  =(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00